version: '3.8'
services:
  backend:
    build: c:/Users/Cjaqu/intellij_workspace/My-App_Backend
    ports:
      - "8080:8080"
    env_file:
      - ./src/main/resources/environment-variables.env
    #environment:
      #DB_USER: ${DB_USER}
      #DB_PASS: ${DB_PASS}
      #DB_INSTANCE: ${DB_INSTANCE}
      #MONGODB_URI: "mongodb+srv://${DB_USER}:${DB_PASS}@${DB_INSTANCE}.pjxdzvf.mongodb.net/?retryWrites=true&w=majority "
      #MONGODB_URI: "mongodb+srv://cjaquiery:uyMOfIs6BtUwxWRr@mywebapp.pjxdzvf.mongodb.net/?retryWrites=true&w=majority"

      #PROFILE: dev

  frontend:
    build: c:/Users/Cjaqu/visualStudioCode-projects/My-App_Frontend
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
